// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: msg.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LesterService_MichaelOffer_FullMethodName = "/LesterService/MichaelOffer"
)

// LesterServiceClient is the client API for LesterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// El servicio define un conjunto de funciones remotas.
type LesterServiceClient interface {
	MichaelOffer(ctx context.Context, in *MichaelRequest, opts ...grpc.CallOption) (*MichaelResponse, error)
}

type lesterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLesterServiceClient(cc grpc.ClientConnInterface) LesterServiceClient {
	return &lesterServiceClient{cc}
}

func (c *lesterServiceClient) MichaelOffer(ctx context.Context, in *MichaelRequest, opts ...grpc.CallOption) (*MichaelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MichaelResponse)
	err := c.cc.Invoke(ctx, LesterService_MichaelOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LesterServiceServer is the server API for LesterService service.
// All implementations must embed UnimplementedLesterServiceServer
// for forward compatibility.
//
// El servicio define un conjunto de funciones remotas.
type LesterServiceServer interface {
	MichaelOffer(context.Context, *MichaelRequest) (*MichaelResponse, error)
	mustEmbedUnimplementedLesterServiceServer()
}

// UnimplementedLesterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLesterServiceServer struct{}

func (UnimplementedLesterServiceServer) MichaelOffer(context.Context, *MichaelRequest) (*MichaelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MichaelOffer not implemented")
}
func (UnimplementedLesterServiceServer) mustEmbedUnimplementedLesterServiceServer() {}
func (UnimplementedLesterServiceServer) testEmbeddedByValue()                       {}

// UnsafeLesterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LesterServiceServer will
// result in compilation errors.
type UnsafeLesterServiceServer interface {
	mustEmbedUnimplementedLesterServiceServer()
}

func RegisterLesterServiceServer(s grpc.ServiceRegistrar, srv LesterServiceServer) {
	// If the following call pancis, it indicates UnimplementedLesterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LesterService_ServiceDesc, srv)
}

func _LesterService_MichaelOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MichaelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LesterServiceServer).MichaelOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LesterService_MichaelOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LesterServiceServer).MichaelOffer(ctx, req.(*MichaelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LesterService_ServiceDesc is the grpc.ServiceDesc for LesterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LesterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LesterService",
	HandlerType: (*LesterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MichaelOffer",
			Handler:    _LesterService_MichaelOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}

const (
	TrevorService_Distraccion_FullMethodName = "/TrevorService/Distraccion"
)

// TrevorServiceClient is the client API for TrevorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrevorServiceClient interface {
	Distraccion(ctx context.Context, in *TrevorRequest, opts ...grpc.CallOption) (*TrevorResponse, error)
}

type trevorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrevorServiceClient(cc grpc.ClientConnInterface) TrevorServiceClient {
	return &trevorServiceClient{cc}
}

func (c *trevorServiceClient) Distraccion(ctx context.Context, in *TrevorRequest, opts ...grpc.CallOption) (*TrevorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrevorResponse)
	err := c.cc.Invoke(ctx, TrevorService_Distraccion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrevorServiceServer is the server API for TrevorService service.
// All implementations must embed UnimplementedTrevorServiceServer
// for forward compatibility.
type TrevorServiceServer interface {
	Distraccion(context.Context, *TrevorRequest) (*TrevorResponse, error)
	mustEmbedUnimplementedTrevorServiceServer()
}

// UnimplementedTrevorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrevorServiceServer struct{}

func (UnimplementedTrevorServiceServer) Distraccion(context.Context, *TrevorRequest) (*TrevorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distraccion not implemented")
}
func (UnimplementedTrevorServiceServer) mustEmbedUnimplementedTrevorServiceServer() {}
func (UnimplementedTrevorServiceServer) testEmbeddedByValue()                       {}

// UnsafeTrevorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrevorServiceServer will
// result in compilation errors.
type UnsafeTrevorServiceServer interface {
	mustEmbedUnimplementedTrevorServiceServer()
}

func RegisterTrevorServiceServer(s grpc.ServiceRegistrar, srv TrevorServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrevorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrevorService_ServiceDesc, srv)
}

func _TrevorService_Distraccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrevorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrevorServiceServer).Distraccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrevorService_Distraccion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrevorServiceServer).Distraccion(ctx, req.(*TrevorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrevorService_ServiceDesc is the grpc.ServiceDesc for TrevorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrevorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TrevorService",
	HandlerType: (*TrevorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Distraccion",
			Handler:    _TrevorService_Distraccion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}

const (
	FranklinService_Distraccion_FullMethodName = "/FranklinService/Distraccion"
)

// FranklinServiceClient is the client API for FranklinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FranklinServiceClient interface {
	Distraccion(ctx context.Context, in *FranklinRequest, opts ...grpc.CallOption) (*FranklinResponse, error)
}

type franklinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFranklinServiceClient(cc grpc.ClientConnInterface) FranklinServiceClient {
	return &franklinServiceClient{cc}
}

func (c *franklinServiceClient) Distraccion(ctx context.Context, in *FranklinRequest, opts ...grpc.CallOption) (*FranklinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FranklinResponse)
	err := c.cc.Invoke(ctx, FranklinService_Distraccion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FranklinServiceServer is the server API for FranklinService service.
// All implementations must embed UnimplementedFranklinServiceServer
// for forward compatibility.
type FranklinServiceServer interface {
	Distraccion(context.Context, *FranklinRequest) (*FranklinResponse, error)
	mustEmbedUnimplementedFranklinServiceServer()
}

// UnimplementedFranklinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFranklinServiceServer struct{}

func (UnimplementedFranklinServiceServer) Distraccion(context.Context, *FranklinRequest) (*FranklinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distraccion not implemented")
}
func (UnimplementedFranklinServiceServer) mustEmbedUnimplementedFranklinServiceServer() {}
func (UnimplementedFranklinServiceServer) testEmbeddedByValue()                         {}

// UnsafeFranklinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FranklinServiceServer will
// result in compilation errors.
type UnsafeFranklinServiceServer interface {
	mustEmbedUnimplementedFranklinServiceServer()
}

func RegisterFranklinServiceServer(s grpc.ServiceRegistrar, srv FranklinServiceServer) {
	// If the following call pancis, it indicates UnimplementedFranklinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FranklinService_ServiceDesc, srv)
}

func _FranklinService_Distraccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FranklinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FranklinServiceServer).Distraccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FranklinService_Distraccion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FranklinServiceServer).Distraccion(ctx, req.(*FranklinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FranklinService_ServiceDesc is the grpc.ServiceDesc for FranklinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FranklinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FranklinService",
	HandlerType: (*FranklinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Distraccion",
			Handler:    _FranklinService_Distraccion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
