// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: msg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MichaelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         string                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MichaelRequest) Reset() {
	*x = MichaelRequest{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MichaelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MichaelRequest) ProtoMessage() {}

func (x *MichaelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MichaelRequest.ProtoReflect.Descriptor instead.
func (*MichaelRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MichaelRequest) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

type MichaelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Botin         uint64                 `protobuf:"varint,1,opt,name=botin,proto3" json:"botin,omitempty"`
	PFranklin     int32                  `protobuf:"varint,2,opt,name=pFranklin,proto3" json:"pFranklin,omitempty"`
	PTrevor       int32                  `protobuf:"varint,3,opt,name=pTrevor,proto3" json:"pTrevor,omitempty"`
	RPolicial     int32                  `protobuf:"varint,4,opt,name=rPolicial,proto3" json:"rPolicial,omitempty"`
	POferta       string                 `protobuf:"bytes,5,opt,name=pOferta,proto3" json:"pOferta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MichaelResponse) Reset() {
	*x = MichaelResponse{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MichaelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MichaelResponse) ProtoMessage() {}

func (x *MichaelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MichaelResponse.ProtoReflect.Descriptor instead.
func (*MichaelResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MichaelResponse) GetBotin() uint64 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *MichaelResponse) GetPFranklin() int32 {
	if x != nil {
		return x.PFranklin
	}
	return 0
}

func (x *MichaelResponse) GetPTrevor() int32 {
	if x != nil {
		return x.PTrevor
	}
	return 0
}

func (x *MichaelResponse) GetRPolicial() int32 {
	if x != nil {
		return x.RPolicial
	}
	return 0
}

func (x *MichaelResponse) GetPOferta() string {
	if x != nil {
		return x.POferta
	}
	return ""
}

type TrevorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notificar     string                 `protobuf:"bytes,1,opt,name=notificar,proto3" json:"notificar,omitempty"`
	PTrevor       int32                  `protobuf:"varint,2,opt,name=pTrevor,proto3" json:"pTrevor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrevorRequest) Reset() {
	*x = TrevorRequest{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrevorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrevorRequest) ProtoMessage() {}

func (x *TrevorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrevorRequest.ProtoReflect.Descriptor instead.
func (*TrevorRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *TrevorRequest) GetNotificar() string {
	if x != nil {
		return x.Notificar
	}
	return ""
}

func (x *TrevorRequest) GetPTrevor() int32 {
	if x != nil {
		return x.PTrevor
	}
	return 0
}

type TrevorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resultado     string                 `protobuf:"bytes,1,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrevorResponse) Reset() {
	*x = TrevorResponse{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrevorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrevorResponse) ProtoMessage() {}

func (x *TrevorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrevorResponse.ProtoReflect.Descriptor instead.
func (*TrevorResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *TrevorResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

type FranklinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notificar     string                 `protobuf:"bytes,1,opt,name=notificar,proto3" json:"notificar,omitempty"`
	PFranklin     int32                  `protobuf:"varint,2,opt,name=pFranklin,proto3" json:"pFranklin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FranklinRequest) Reset() {
	*x = FranklinRequest{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FranklinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FranklinRequest) ProtoMessage() {}

func (x *FranklinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FranklinRequest.ProtoReflect.Descriptor instead.
func (*FranklinRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *FranklinRequest) GetNotificar() string {
	if x != nil {
		return x.Notificar
	}
	return ""
}

func (x *FranklinRequest) GetPFranklin() int32 {
	if x != nil {
		return x.PFranklin
	}
	return 0
}

type FranklinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resultado     string                 `protobuf:"bytes,1,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FranklinResponse) Reset() {
	*x = FranklinResponse{}
	mi := &file_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FranklinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FranklinResponse) ProtoMessage() {}

func (x *FranklinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FranklinResponse.ProtoReflect.Descriptor instead.
func (*FranklinResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *FranklinResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\"&\n" +
	"\x0eMichaelRequest\x12\x14\n" +
	"\x05offer\x18\x01 \x01(\tR\x05offer\"\x97\x01\n" +
	"\x0fMichaelResponse\x12\x14\n" +
	"\x05botin\x18\x01 \x01(\x04R\x05botin\x12\x1c\n" +
	"\tpFranklin\x18\x02 \x01(\x05R\tpFranklin\x12\x18\n" +
	"\apTrevor\x18\x03 \x01(\x05R\apTrevor\x12\x1c\n" +
	"\trPolicial\x18\x04 \x01(\x05R\trPolicial\x12\x18\n" +
	"\apOferta\x18\x05 \x01(\tR\apOferta\"G\n" +
	"\rTrevorRequest\x12\x1c\n" +
	"\tnotificar\x18\x01 \x01(\tR\tnotificar\x12\x18\n" +
	"\apTrevor\x18\x02 \x01(\x05R\apTrevor\".\n" +
	"\x0eTrevorResponse\x12\x1c\n" +
	"\tresultado\x18\x01 \x01(\tR\tresultado\"M\n" +
	"\x0fFranklinRequest\x12\x1c\n" +
	"\tnotificar\x18\x01 \x01(\tR\tnotificar\x12\x1c\n" +
	"\tpFranklin\x18\x02 \x01(\x05R\tpFranklin\"0\n" +
	"\x10FranklinResponse\x12\x1c\n" +
	"\tresultado\x18\x01 \x01(\tR\tresultado2B\n" +
	"\rLesterService\x121\n" +
	"\fMichaelOffer\x12\x0f.MichaelRequest\x1a\x10.MichaelResponse2?\n" +
	"\rTrevorService\x12.\n" +
	"\vDistraccion\x12\x0e.TrevorRequest\x1a\x0f.TrevorResponse2E\n" +
	"\x0fFranklinService\x122\n" +
	"\vDistraccion\x12\x10.FranklinRequest\x1a\x11.FranklinResponseB\x14Z\x12./grpc/proto;protob\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msg_proto_goTypes = []any{
	(*MichaelRequest)(nil),   // 0: MichaelRequest
	(*MichaelResponse)(nil),  // 1: MichaelResponse
	(*TrevorRequest)(nil),    // 2: TrevorRequest
	(*TrevorResponse)(nil),   // 3: TrevorResponse
	(*FranklinRequest)(nil),  // 4: FranklinRequest
	(*FranklinResponse)(nil), // 5: FranklinResponse
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: LesterService.MichaelOffer:input_type -> MichaelRequest
	2, // 1: TrevorService.Distraccion:input_type -> TrevorRequest
	4, // 2: FranklinService.Distraccion:input_type -> FranklinRequest
	1, // 3: LesterService.MichaelOffer:output_type -> MichaelResponse
	3, // 4: TrevorService.Distraccion:output_type -> TrevorResponse
	5, // 5: FranklinService.Distraccion:output_type -> FranklinResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
