docker-franklin:
	docker run --rm --name franklin \
		-p 50053:50053 \
		-e RABBITMQ_HOST=10.35.168.89 \
		-e RABBITMQ_PORT=5672 \
		-e RABBITMQ_DEFAULT_USER=user \
		-e RABBITMQ_DEFAULT_PASS=pass \
		franklin
