docker-trevor:
	docker run --rm --name trevor \
		-p 50052:50052 \
		-e RABBITMQ_HOST=10.35.168.89 \
		-e RABBITMQ_PORT=5672 \
		-e RABBITMQ_DEFAULT_USER=user \
		-e RABBITMQ_DEFAULT_PASS=pass \
		trevor